### ISSUE TITLE
modification de download_data pour gérer le cas des dataframes à None

### ISSUE THREAD

**Issue by skeletozaure** [CryptoRobotFr/cBot-Project#1]
Hello,

Quand un dataframe est à None en retour de get_historical_from_api (ce qui peut arriver selon les paires et le timeframe, par exemple le SHIB en timeframe 5mn sur Bybit), download_data se plante. Je propose une petite modification : 
---> if df is not None and len(df) > 0
Et peut être un petit print pour avertir que la paire n'existe pas.

Ce qui donnerait : 

        for symbol in symbols:
            for tf in timeframes:
                print(f'-> downloding symbol {symbol} for timeframe {tf}')
                df = self.get_historical_from_api(symbol=symbol, timeframe=tf, start_date=start_date)
                if df is not None and len(df) > 0:

ça fonctionne bien dans mon cas.
Merci
A+

**Comment by CryptoRobotFr** [comment]
Hello merci pour la proposition c'est bon j'ai ajouté directement tes propositions sur la branche main (la prochaine fois tu peux même faire une merge request directe comme ça j'ai juste à accepter la modification). Merci de ta contribution ;)
